#build settings

#theme: jekyll-athena
#theme_color: dark
markdown: kramdown

#personal settings
title: Eric Li
description: Mathematics Student at Carnegie Mellon University
github_username: ericli
linkedin_profile: lieric2
email: ericl2@andrew.cmu.edu
url: "https://lieric.com"
