#build settings

remote_theme: broccolini/swiss
theme_color: white
markdown: kramdown

#personal settings
title: Eric Li
description: Mathematics Student at Carnegie Mellon University
github_username: ericli
linkedin_profile: lieric2
email: ericl2@andrew.cmu.edu
url: "lieric.com"


