title: Eric Li
description: Mathematics Student at Carnegie Mellon University
email: ericl2@andrew.cmu.edu

github_username: ericli
linkedin_profile: lieric2
email: ericl2@andrew.cmu.edu
url: "https://lieric.com"

markdown: kramdown

